#!/bin/bash

# NOTE: should be run as root user

ROOT=$(cd "$(dirname "$0")/.."; pwd)
echo "Building OctopushOS for Bela..."

# Install dependencies
apt-get install clang git ladspa-sdk freeglut3-dev g++ libasound2-dev libcurl4-openssl-dev libfreetype6-dev libjack-jackd2-dev libx11-dev libxcomposite-dev libxcursor-dev libxinerama-dev libxrandr-dev mesa-common-dev webkit2gtk-4.0 juce-tools libusb-1.0-0-dev

# Enable swap (otherwise we'll run into memory problems when compiling)
# TODO: run this step only if it has not been enabled before
#sudo dd if=/dev/zero of=/swapfile bs=64M count=16
#sudo mkswap /swapfile
#sudo swapon /swapfile

# Build
cd "$ROOT/Builds/LinuxMakefile"
make clean
make CONFIG=Release -j2

# Disable swap
# TODO: run this step only it swap was enabled
# sudo swapoff /swapfile
# sudo rm /swapfile 
