#!/bin/bash

ROOT=$(cd "$(dirname "$0")/../OctopushOS/"; pwd)

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    if [[ "$(uname -m)" == "armv"* ]]; then
      # Raspbain
      echo "BUILDING DEBUG OCTOPUSH FOR RASPBAIN"
      cd "$ROOT/Builds/Raspbain"
    else
      # Linux
      echo "BUILDING DEBUG OCTOPUSH FOR LINUX"
      cd "$ROOT/Builds/LinuxMakefile"
    fi
    #make clean
    make CONFIG=Debug -j2
elif [[ "$OSTYPE" == "darwin"* ]]; then
    # Mac OSX
    echo "BUILDING DEBUG OCTOPUSH FOR MACOS"
    cd "$ROOT/Builds/MacOSX"
    xcodebuild -configuration Debug GCC_PREPROCESSOR_DEFINITIONS='$GCC_PREPROCESSOR_DEFINITIONS JUCER_ENABLE_GPL_MODE=1' LLVM_LTO=NO
fi
