#!/bin/bash

ROOT=$(cd "$(dirname "$0")/../OctopushOS/"; pwd)
echo "Building Projucer..."

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    # Linux
    PROJUCER_ROOT=$ROOT/3rdParty/juce/extras/Projucer/Builds/LinuxMakefile
    PROJUCER_EXE=$PROJUCER_ROOT/build/Release/Projucer
    cd "$PROJUCER_ROOT"
    make clean
    make CONFIG=Release -j2
elif [[ "$OSTYPE" == "darwin"* ]]; then
    # Mac OSX
    PROJUCER_ROOT=$ROOT/3rdParty/juce/extras/Projucer/Builds/MacOSX
    PROJUCER_EXE=$PROJUCER_ROOT/build/Release/Projucer.app/Contents/MacOS/Projucer
    cd "$PROJUCER_ROOT"
    xcodebuild -configuration Release GCC_PREPROCESSOR_DEFINITIONS='$GCC_PREPROCESSOR_DEFINITIONS JUCER_ENABLE_GPL_MODE=1' LLVM_LTO=NO
fi
